$ ->

  ### 螟夜Κ繝ｪ繝ｳ繧ｯ縺ｯ譁ｰ隕上え繧｣繝ｳ繝峨え縺ｧ髢九￥ ###

  $('a.external').attr 'target', '_blank'
  $('a.help').attr 'target', '_blank'
  $('div#footer a[href^=\'http://www.redmine.org/\']').attr 'target', '_blank'
  lang = if $('a.help').text() == '繝倥Ν繝�' then 'ja' else $('html').attr('lang')
  if lang == 'ja'

    ### 險隱槭′譌･譛ｬ隱槭�縺ｨ縺阪�繝倥Ν繝励�繝ｪ繝ｳ繧ｯ蜈医ｒRedmine.JP縺ｮ譌･譛ｬ隱櫁ｨｳ縺ｫ縺吶ｋ ###

    $('a.help').attr 'href', 'http://redmine.jp/guide/'

    ### 讀懃ｴ｢縺ｫ縺翫￠繧九せ繧ｳ繝ｼ繝励ｒ讀懃ｴ｢繝懊ャ繧ｯ繧ｹ縺ｮ繝励Ξ繝ｼ繧ｹ繝帙Ν繝繝ｼ縺ｫ陦ｨ遉ｺ ###

    $('body').attr('class').match /controller-[\S]+/
    controllerName = RegExp.lastMatch
    placeholderText = 'Redmine蜀�ｒ讀懃ｴ｢'
    placeholderStrings = [
      {
        controller: 'controller-issues'
        text: '繝√こ繝�ヨ繧呈､懃ｴ｢'
      }
      {
        controller: 'controller-news'
        text: '繝九Η繝ｼ繧ｹ繧呈､懃ｴ｢'
      }
      {
        controller: 'controller-documents'
        text: '譁�嶌繧呈､懃ｴ｢'
      }
      {
        controller: 'controller-changesets'
        text: '譖ｴ譁ｰ螻･豁ｴ繧呈､懃ｴ｢'
      }
      {
        controller: 'controller-wiki_pages'
        text: 'Wiki繝壹�繧ｸ繧呈､懃ｴ｢'
      }
      {
        controller: 'controller-messages'
        text: '繝｡繝�そ繝ｼ繧ｸ繧呈､懃ｴ｢'
      }
    ]
    jQuery.each placeholderStrings, ->
      if controllerName == @controller
        placeholderText = @text
        return false
      return
    $('#quick-search input#q').attr 'placeholder', placeholderText
  return

# ---
# generated by js2coffee 2.2.0