# generic layout specific responsive stuff goes here

openFlyout = ->
  $('html').addClass 'flyout-is-active'
  $('#wrapper2').on 'click', (e) ->
    e.preventDefault()
    e.stopPropagation()
    closeFlyout()
    return
  return

closeFlyout = ->
  $('html').removeClass 'flyout-is-active'
  $('#wrapper2').off 'click'
  return

isMobile = ->
  $('.js-flyout-menu-toggle-button').is ':visible'

setupFlyout = ->
  mobileInit = false
  desktopInit = false

  ### click handler for mobile menu toggle ###

  ### menu init function for dom detaching and appending on mobile / desktop view ###

  initMenu = ->

    _initMobileMenu = ->

      ### only init mobile menu, if it hasn't been done yet ###

      if !mobileInit
        $('#main-menu > ul').detach().appendTo '.js-project-menu'
        $('#top-menu > ul').detach().appendTo '.js-general-menu'
        $('#sidebar > *').detach().appendTo '.js-sidebar'
        $('#account > ul').detach().appendTo '.js-profile-menu'
        mobileInit = true
        desktopInit = false
      return

    _initDesktopMenu = ->
      if !desktopInit
        $('.js-project-menu > ul').detach().appendTo '#main-menu'
        $('.js-general-menu > ul').detach().appendTo '#top-menu'
        $('.js-sidebar > *').detach().appendTo '#sidebar'
        $('.js-profile-menu > ul').detach().appendTo '#account'
        desktopInit = true
        mobileInit = false
      return

    if isMobile()
      _initMobileMenu()
    else
      _initDesktopMenu()
    return

  $('.js-flyout-menu-toggle-button').on 'click', (e) ->
    e.preventDefault()
    e.stopPropagation()
    if $('html').hasClass('flyout-is-active')
      closeFlyout()
    else
      openFlyout()
    return

  ### bind resize handler ###

  $(window).resize ->
    initMenu()
    return
  # init menu on page load
  initMenu()
  return

$(document).ready setupFlyout

# ---
# generated by js2coffee 2.2.0